name = "plinth"
version = "0.1.8"
description = "Bindings to Node.js and browser platform APIs"
target = "javascript"

# Fill out these fields if you intend to generate HTML documentation or publish
# your project to the Hex package manager.
#
licences = ["Apache-2.0"]
repository = { type = "github", user = "Crowdhailer", repo = "plinth" }
gleam = ">= 0.32.0"
# links = [{ title = "Website", href = "https://gleam.run" }]

[dependencies]
gleam_stdlib = "~> 0.29"
gleam_javascript = "~> 0.4"
gleam_json = "~> 0.7"

[dev-dependencies]
gleeunit = "~> 1.0"
