name = "plinth"
version = "0.7.2"
description = "Bindings to Node.js and browser platform APIs"
target = "javascript"

licences = ["Apache-2.0"]
repository = { type = "github", user = "Crowdhailer", repo = "plinth" }
gleam = ">= 1.9.0"

[dependencies]
gleam_stdlib = ">= 0.29.0 and < 2.0.0"
gleam_javascript = ">= 1.0.0 and < 2.0.0"
gleam_json = ">= 1.0.0 and < 4.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
